const { contextBridge, ipcRenderer } = require('electron');
// Deliberately narrow. The renderer can ask for data and nothing else -- it makes no network
// requests and never sees a key. Everything that touches the outside world stays in main.
contextBridge.exposeInMainWorld('mcii', {
  getTokens: () => ipcRenderer.invoke('tokens:list'),
  refresh: (ca) => ipcRenderer.invoke('tokens:refresh', ca),
  setPosition: (ca, tokens) => ipcRenderer.invoke('tokens:setPosition', { ca, tokens }),
  search: (q) => ipcRenderer.invoke('tokens:search', q),
  addToken: (ca, sym) => ipcRenderer.invoke('watchlist:add', { ca, sym }),
  removeToken: (ca) => ipcRenderer.invoke('watchlist:remove', ca),
  renameToken: (ca, nick) => ipcRenderer.invoke('watchlist:rename', { ca, nick }),
  discover: () => ipcRenderer.invoke('discover:latest'),
  collectionHealth: () => ipcRenderer.invoke('collection:health'),
  sector: () => ipcRenderer.invoke('sector:latest'),
  tickerCollisions: () => ipcRenderer.invoke('tickers:collisions'),
  openExternal: (url) => ipcRenderer.invoke('shell:open', url),
  owner: () => ipcRenderer.invoke('journal:owner'),
  setOwner: (n) => ipcRenderer.invoke('journal:setOwner', n),
  allOwners: () => ipcRenderer.invoke('journal:owners'),
  theses: () => ipcRenderer.invoke('journal:theses'),
  saveThesis: (t) => ipcRenderer.invoke('journal:saveThesis', t),
  forecasts: (owner) => ipcRenderer.invoke('journal:forecasts', owner),
  addForecast: (f) => ipcRenderer.invoke('journal:addForecast', f),
  resolveForecast: (id, outcome, lesson) => ipcRenderer.invoke('journal:resolve', { id, outcome, lesson }),
  calibration: (owner) => ipcRenderer.invoke('journal:calibration', owner),
  screenLatest: () => ipcRenderer.invoke('screen:latest'),
  socialFor: (ca) => ipcRenderer.invoke('social:token', ca),
  allAlerts: () => ipcRenderer.invoke('alerts:all'),
  cachedTokens: () => ipcRenderer.invoke('tokens:cached'),
  orionStatus: () => ipcRenderer.invoke('orion:status'),
  orionAsk: (text) => ipcRenderer.invoke('orion:ask', text),
  orionLogin: () => ipcRenderer.invoke('orion:login'),
  historySeries: (ca, field, days) => ipcRenderer.invoke('history:series', { ca, field, days }),
  onLive: (cb) => ipcRenderer.on('live', (_e, t) => cb(t)),
  onLiveAlert: (cb) => ipcRenderer.on('live-alert', (_e, a) => cb(a)),
  onRefreshed: (cb) => ipcRenderer.on('refreshed', () => cb()),
  onProgress: (cb) => ipcRenderer.on('progress', (_e, m) => cb(m)),
  checkForUpdates: () => ipcRenderer.invoke('update:check'),
  applyUpdate: () => ipcRenderer.invoke('update:apply'),
  shareChanges: (message) => ipcRenderer.invoke('update:share', message),
  restartApp: () => ipcRenderer.invoke('update:restart'),
  onUpdateStatus: (cb) => ipcRenderer.on('update-status', (_e, r) => cb(r)),
});
