const { contextBridge, ipcRenderer } = require('electron');
// Deliberately narrow. The renderer can ask for data and nothing else -- it makes no network
// requests and never sees a key. Everything that touches the outside world stays in main.
contextBridge.exposeInMainWorld('mcii', {
  getTokens: () => ipcRenderer.invoke('tokens:list'),
  refresh: (ca) => ipcRenderer.invoke('tokens:refresh', ca),
  setPosition: (ca, tokens) => ipcRenderer.invoke('tokens:setPosition', { ca, tokens }),
  search: (q) => ipcRenderer.invoke('tokens:search', q),
  addToken: (ca, sym) => ipcRenderer.invoke('watchlist:add', { ca, sym }),
  removeToken: (ca) => ipcRenderer.invoke('watchlist:remove', ca),
  renameToken: (ca, nick) => ipcRenderer.invoke('watchlist:rename', { ca, nick }),
  discover: () => ipcRenderer.invoke('discover:latest'),
  collectionHealth: () => ipcRenderer.invoke('collection:health'),
  sector: () => ipcRenderer.invoke('sector:latest'),
  tickerCollisions: () => ipcRenderer.invoke('tickers:collisions'),
  openExternal: (url) => ipcRenderer.invoke('shell:open', url),
  owner: () => ipcRenderer.invoke('journal:owner'),
  setOwner: (n) => ipcRenderer.invoke('journal:setOwner', n),
  allOwners: () => ipcRenderer.invoke('journal:owners'),
  theses: () => ipcRenderer.invoke('journal:theses'),
  saveThesis: (t) => ipcRenderer.invoke('journal:saveThesis', t),
  forecasts: (owner) => ipcRenderer.invoke('journal:forecasts', owner),
  addForecast: (f) => ipcRenderer.invoke('journal:addForecast', f),
  resolveForecast: (id, outcome, lesson) => ipcRenderer.invoke('journal:resolve', { id, outcome, lesson }),
  calibration: (owner) => ipcRenderer.invoke('journal:calibration', owner),
  notes: () => ipcRenderer.invoke('journal:notes'),
  addNote: (text) => ipcRenderer.invoke('journal:addNote', { text }),
  screenLatest: () => ipcRenderer.invoke('screen:latest'),
  socialFor: (ca) => ipcRenderer.invoke('social:token', ca),
  allAlerts: () => ipcRenderer.invoke('alerts:all'),
  cachedTokens: () => ipcRenderer.invoke('tokens:cached'),
  orionStatus: () => ipcRenderer.invoke('orion:status'),
  orionAsk: (text) => ipcRenderer.invoke('orion:ask', text),
  orionLogin: () => ipcRenderer.invoke('orion:login'),
  historySeries: (ca, field, days) => ipcRenderer.invoke('history:series', { ca, field, days }),
  growthQuality: () => ipcRenderer.invoke('growth:quality'),
  calendarList: () => ipcRenderer.invoke('calendar:list'),
  calendarUpcoming: (withinDays) => ipcRenderer.invoke('calendar:upcoming', withinDays),
  // Portfolio. Public wallet addresses in, holdings out -- the renderer never sees a key,
  // because no key exists anywhere in this app.
  wallets: () => ipcRenderer.invoke('wallet:list'),
  setWallet: (venue, address) => ipcRenderer.invoke('wallet:set', { venue, address }),
  portfolio: () => ipcRenderer.invoke('portfolio:load'),
  portfolioSeries: (days) => ipcRenderer.invoke('portfolio:series', { days }),
  // The venue rooms. The renderer positions them and says when to hide; it never gets a handle
  // on the page itself, and the venue page never gets a handle on this bridge.
  venueList: () => ipcRenderer.invoke('venue:list'),
  venueOpen: (id, bounds) => ipcRenderer.invoke('venue:open', { id, bounds }),
  venueHide: (id) => ipcRenderer.invoke('venue:hide', id),
  venueBounds: (id, bounds) => ipcRenderer.invoke('venue:bounds', { id, bounds }),
  venueStatus: (id) => ipcRenderer.invoke('venue:status', id),
  venueReload: (id) => ipcRenderer.invoke('venue:reload', id),
  venueBack: (id) => ipcRenderer.invoke('venue:back', id),
  venueExternal: (id) => ipcRenderer.invoke('venue:external', id),
  venueAppWindow: (id) => ipcRenderer.invoke('venue:appWindow', id),
  venueSignOut: (id) => ipcRenderer.invoke('venue:signOut', id),
  onLive: (cb) => ipcRenderer.on('live', (_e, t) => cb(t)),
  onLiveAlert: (cb) => ipcRenderer.on('live-alert', (_e, a) => cb(a)),
  onRefreshed: (cb) => ipcRenderer.on('refreshed', () => cb()),
  onProgress: (cb) => ipcRenderer.on('progress', (_e, m) => cb(m)),
  checkForUpdates: () => ipcRenderer.invoke('update:check'),
  applyUpdate: () => ipcRenderer.invoke('update:apply'),
  shareChanges: (message) => ipcRenderer.invoke('update:share', message),
  restartApp: () => ipcRenderer.invoke('update:restart'),
  onUpdateStatus: (cb) => ipcRenderer.on('update-status', (_e, r) => cb(r)),
});
